# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JF_ARTIFACTORY_1: ${{ secrets.JF_ARTIFACTORY_SECRET_1 }}
      JFROG_BUILD_STATUS: PASS
      PYTHON_VERSION: 3.9
      PYTHON_REPO: urs-python
      GENERIC_REPO: urs-generic
    steps:
      - uses: actions/checkout@v2

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v1.2.0

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v2.2.2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Ping Artifactory
        run: |
            jfrog rt ping
            jfrog rt c show
            
      - name: Configure JFrog CLI and PIP client
        run: jfrog rt pip-config --repo-resolve ${{ env.PYTHON_REPO }} --server-id-resolve art1

      - name: Install dependencies
        run: jfrog rt pip-install -r src/requirements.txt --no-cache-dir  --build-name=$JFROG_CLI_BUILD_NAME --build-number=$JFROG_CLI_BUILD_NUMBER --module=python_deps

      - name: Package and upload webapp
        run: |
          tar -czvf webapp_python.tar.gz src/*.yaml src/*.txt src/*.py
          jfrog rt upload webapp_python.tar.gz ${{ env.GENERIC_REPO }} --build-name $JFROG_CLI_BUILD_NAME --build-number $JFROG_CLI_BUILD_NUMBER

      - name: Publish Build Info
        run: |
          # Collect environment variables for the build
          jfrog rt bce $JFROG_CLI_BUILD_NAME $JFROG_CLI_BUILD_NUMBER
          # Collect VCS details from git and add them to the build
          jfrog rt bag $JFROG_CLI_BUILD_NAME $JFROG_CLI_BUILD_NUMBER
          # Publish build info
          jfrog rt bp $JFROG_CLI_BUILD_NAME $JFROG_CLI_BUILD_NUMBER
